### ISSUE TITLE
More corner/slope/tip pieces for half blocks

### ISSUE THREAD

**Issue by rcdailey** [enenra/aqdse#66]
I'm building a ship with a row of half blocks on the top of its hull. The corner are too high and expect to join with full block height. I've made a quick example in creative to show you what I'm trying to do. Notice the 2x1x1 corner and tip are too high:

![image](https://user-images.githubusercontent.com/1768054/101287796-32292700-37b8-11eb-8631-a9b6c533c0a8.png)

![image](https://user-images.githubusercontent.com/1768054/101287799-36554480-37b8-11eb-8262-868af6c96830.png)

Could you design more corner tips that meet with half blocks? I'm assuming the size of one side of the tip just need to be reduced by half, so that it would take 4 of these blocks to meet up with a full height block instead of just 2 currently. This would probably be a 4x1x1 tip?

**Comment by rcdailey** [comment]
Here is another example of the corners I'm trying to fill in. Note the missing pieces.

![image](https://user-images.githubusercontent.com/1768054/101288097-479f5080-37ba-11eb-8bfb-6220217b7e77.png)

The side pieces I'm using are:

![image](https://user-images.githubusercontent.com/1768054/101288090-3a826180-37ba-11eb-8ed3-1820968c1016.png)

**Comment by enenra** [comment]
Hi,

As stated on the mod page, I do not take requests for more blocks.
